robot_cfg:
  kinematics:
    base_link: base_link
    link_names: ['left_tool_frame', 'right_tool_frame']
    collision_link_names:
    - base_link
    - ewellix_lift_top_link
    - right_base_link
    - left_base_link
    - right_shoulder_link
    - left_shoulder_link
    - right_half_arm_1_link
    - left_half_arm_1_link
    - right_half_arm_2_link
    - left_half_arm_2_link
    - right_forearm_link
    - left_forearm_link
    - right_spherical_wrist_1_link
    - left_spherical_wrist_1_link
    - right_spherical_wrist_2_link
    - left_spherical_wrist_2_link
    - right_bracelet_link
    - left_bracelet_link
    - right_arm_robotiq_arg2f_base_link
    - left_arm_robotiq_arg2f_base_link
    - left_arm_left_outer_finger
    - left_arm_right_outer_finger
    - right_arm_left_outer_finger
    - right_arm_right_outer_finger
    - left_arm_left_inner_finger
    - left_arm_right_inner_finger
    - right_arm_left_inner_finger
    - right_arm_right_inner_finger
    - left_arm_right_finger_mount
    - left_arm_left_finger_mount
    - left_arm_right_fingertip
    - left_arm_left_fingertip
    - right_arm_right_finger_mount
    - right_arm_left_finger_mount
    - right_arm_right_fingertip
    - right_arm_left_fingertip
    collision_sphere_buffer: 0.0
    collision_spheres:
      base_link:
        - "center": [0.0, 0.0, 0.364]
          "radius": 0.10279
        - "center": [0.0, 0.0, 0.54]
          "radius": 0.10279
      ewellix_lift_top_link:
        - "center": [0.0, 0.0, -0.193]
          "radius": 0.1
        - "center": [0.0, 0.0, -0.071]
          "radius": 0.1
        - "center": [0.0, 0.0, 0.067]
          "radius": 0.05
        - "center": [0.0, 0.0, 0.169]
          "radius": 0.05
      left_base_link:
        - "center": [-0.0, 0.163, 0.175]
          "radius": 0.0571
        - "center": [0.001, 0.104, 0.174]
          "radius": 0.0571
        - "center": [0.001, 0.048, 0.179]
          "radius": 0.04712
      left_shoulder_link:
        - "center": [-0.128, -0.013, 0.001]
          "radius": 0.05445
        - "center": [-0.077, -0.029, -0.0]
          "radius": 0.06
        - "center": [-0.03, 0.001, -0.002]
          "radius": 0.05445
      left_half_arm_1_link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.05445
        - "center": [-0.021, -0.005, 0.0]
          "radius": 0.05445
        - "center": [-0.042, -0.059, 0.001]
          "radius": 0.03
        - "center": [-0.004, -0.192, 0.0]
          "radius": 0.05445
        - "center": [-0.024, -0.112, 0.0]
          "radius": 0.03445
        - "center": [-0.021, -0.157, 0.0]
          "radius": 0.03445
      left_half_arm_2_link:
        - "center": [-0.118, -0.03, 0.002]
          "radius": 0.02
        - "center": [-0.069, -0.008, 0.003]
          "radius": 0.04489
        - "center": [-0.017, -0.002, 0.005]
          "radius": 0.05
        - "center": [-0.212, -0.018, 0.001]
          "radius": 0.04489
        - "center": [-0.156, -0.03, 0.002]
          "radius": 0.02489
      left_forearm_link:
        - "center": [-0.025, -0.112, 0.0]
          "radius": 0.02586
        - "center": [-0.029, -0.08, 0.0]
          "radius": 0.02472
        - "center": [-0.04, -0.033, 0.0]
          "radius": 0.02472
        - "center": [-0.005, -0.194, 0.0]
          "radius": 0.04586
        - "center": [-0.017, 0.0, -0.0]
          "radius": 0.04472
      left_spherical_wrist_1_link:
        - "center": [-0.056, -0.021, 0.0]
          "radius": 0.04
        - "center": [-0.104, -0.019, 0.001]
          "radius": 0.04547
        - "center": [-0.019, 0.005, 0.0]
          "radius": 0.04547
      left_spherical_wrist_2_link:
        - "center": [-0.018, -0.003, 0.001]
          "radius": 0.04571
        - "center": [0.0, -0.097, 0.0]
          "radius": 0.04571
        - "center": [-0.019, -0.045, -0.0]
          "radius": 0.04571
      left_bracelet_link:
        - "center": [-0.045, 0.001, -0.0]
          "radius": 0.04555
        - "center": [-0.051, -0.062, -0.022]
          "radius": 0.02555
        - "center": [-0.051, -0.059, 0.013]
          "radius": 0.02555
      left_arm_robotiq_arg2f_base_link:
        - "center": [0.001, -0.003, 0.032]
          "radius": 0.05315
      left_arm_left_inner_knuckle:
        - "center": [-0.005, -0.037, 0.09]
          "radius": 0.02
      left_arm_left_inner_finger:
        - "center": [0.0, -0.01, 0.008]
          "radius": 0.01688
      left_arm_left_finger_mount:
        - "center": [-0.006, 0.002, -0.004]
          "radius": 0.02404
      left_arm_left_fingertip:
        - "center": [0.021, -0.015, -0.043]
          "radius": 0.02398
        - "center": [0.017, -0.013, -0.072]
          "radius": 0.01898
        - "center": [0.008, -0.016, -0.095]
          "radius": 0.00898
      left_arm_left_outer_knuckle:
        - "center": [0.004, -0.058, 0.062]
          "radius": 0.02
      left_arm_left_outer_finger:
        - "center": [0.001, 0.006, 0.035]
          "radius": 0.015
      left_arm_right_inner_knuckle:
        - "center": [-0.0, 0.04, 0.087]
          "radius": 0.02
      left_arm_right_inner_finger:
        - "center": [0.0, 0.039, 0.045]
          "radius": 0.01688
      left_arm_right_finger_mount:
        - "center": [-0.004, 0.006, 0.006]
          "radius": 0.026
      left_arm_right_fingertip:
        - "center": [0.024, -0.006, -0.033]
          "radius": 0.02398
        - "center": [0.018, -0.013, -0.063]
          "radius": 0.01898
        - "center": [0.011, -0.014, -0.09]
          "radius": 0.00898
      left_arm_right_outer_knuckle:
        - "center": [0.005, 0.052, 0.057]
          "radius": 0.02
      left_arm_right_outer_finger:
        - "center": [0.001, 0.0, 0.024]
          "radius": 0.02
      right_base_link:
        - "center": [0.0, -0.05, 0.174]
          "radius": 0.0501
        - "center": [0.0, -0.096, 0.174]
          "radius": 0.0501
        - "center": [0.0, -0.147, 0.175]
          "radius": 0.05
      right_shoulder_link:
        - "center": [-0.09, -0.013, 0.0]
          "radius": 0.04445
        - "center": [-0.04, -0.012, 0.0]
          "radius": 0.04445
        - "center": [-0.008, 0.003, 0.0]
          "radius": 0.04445
        - "center": [-0.129, -0.004, -0.0]
          "radius": 0.05
      right_half_arm_1_link:
        - "center": [-0.035, 0.004, 0.0]
          "radius": 0.04445
        - "center": [-0.037, -0.039, 0.0]
          "radius": 0.04445
        - "center": [-0.007, -0.192, -0.0]
          "radius": 0.04445
        - "center": [-0.015, -0.144, 0.0]
          "radius": 0.04445
        - "center": [-0.032, -0.094, 0.0]
          "radius": 0.04445
      right_half_arm_2_link:
        - "center": [-0.218, -0.011, 0.002]
          "radius": 0.04489
        - "center": [-0.109, -0.017, 0.0]
          "radius": 0.04489
        - "center": [-0.07, -0.014, 0.0]
          "radius": 0.04489
        - "center": [-0.16, -0.018, 0.0]
          "radius": 0.04489
        - "center": [-0.029, -0.0, 0.0]
          "radius": 0.05
      right_forearm_link:
        - "center": [-0.005, -0.19, 0.0]
          "radius": 0.04586
        - "center": [-0.03, 0.005, 0.0]
          "radius": 0.04472
        - "center": [-0.036, -0.094, 0.0]
          "radius": 0.04472
        - "center": [-0.045, -0.027, 0.0]
          "radius": 0.04472
        - "center": [-0.024, -0.149, 0.0]
          "radius": 0.04586
      right_spherical_wrist_1_link:
        - "center": [-0.105, -0.013, 0.0]
          "radius": 0.04547
        - "center": [-0.019, -0.007, -0.0]
          "radius": 0.04547
        - "center": [-0.068, -0.013, 0.0]
          "radius": 0.04547
      right_spherical_wrist_2_link:
        - "center": [-0.02, 0.011, 0.0]
          "radius": 0.04571
        - "center": [-0.004, -0.094, 0.0]
          "radius": 0.04571
        - "center": [-0.034, -0.039, 0.0]
          "radius": 0.04571
      right_bracelet_link:
        - "center": [-0.029, 0.004, 0.0]
          "radius": 0.04555
        - "center": [-0.069, -0.005, 0.0]
          "radius": 0.04555
        - "center": [-0.057, -0.051, 0.015]
          "radius": 0.03555
        - "center": [-0.056, -0.051, -0.014]
          "radius": 0.03555
      right_arm_robotiq_arg2f_base_link:
        - "center": [0.002, -0.046, -0.01]
          "radius": 0.0474
      right_arm_left_inner_knuckle:
        - "center": [-0.009, -0.095, 0.003]
          "radius": 0.02402
      right_arm_left_outer_knuckle:
        - "center": [-0.038, -0.062, -0.0]
          "radius": 0.02427
      right_arm_left_outer_finger:
        - "center": [-0.038, -1.325, 1.062]
          "radius": 0.02438
        - "center": [-0.047, -1.3, 1.07]
          "radius": 0.02438
      right_arm_left_inner_finger:
        - "center": [-0.013, -1.335, 1.065]
          "radius": 0.01688
      right_arm_right_finger_mount:
        - "center": [-0.022, -1.368, 1.055]
          "radius": 0.02404
      right_arm_right_fingertip:
        - "center": [-0.016, -1.402, 1.053]
          "radius": 0.02398
        - "center": [-0.013, -1.436, 1.054]
          "radius": 0.01398
      right_arm_right_inner_knuckle:
        - "center": [0.009, -0.095, 0.01]
          "radius": 0.01902
      right_arm_right_outer_knuckle:
        - "center": [0.034, -0.057, 0.0]
          "radius": 0.02422
      right_arm_right_outer_finger:
        - "center": [0.048, -1.301, 1.07]
          "radius": 0.02437
        - "center": [0.033, -1.329, 1.07]
          "radius": 0.01937
      right_arm_right_inner_finger:
        - "center": [0.013, -1.335, 1.065]
          "radius": 0.01689
      right_arm_left_finger_mount:
        - "center": [0.022, -1.37, 1.055]
          "radius": 0.025
      right_arm_left_fingertip:
        - "center": [0.019, -1.402, 1.055]
          "radius": 0.02398
        - "center": [0.013, -1.436, 1.053]
          "radius": 0.01398

    ee_link: left_tool_frame
    self_collision_buffer:
      base_link: 0.0
      ewellix_lift_top_link: 0.0
      right_base_link: 0.0
      left_base_link: 0.0
      right_forearm_link: 0.0
      left_forearm_link: 0.0
      right_half_arm_1_link: 0.0
      left_half_arm_1_link: 0.0
      right_half_arm_2_link: 0.0
      left_half_arm_2_link: 0.0
      right_shoulder_link: 0.0
      left_shoulder_link: 0.0
      right_spherical_wrist_1_link : 0.0
      left_spherical_wrist_1_link : 0.0
      right_spherical_wrist_2_link : 0.0
      left_spherical_wrist_2_link : 0.0
      right_bracelet_link: 0.0
      left_bracelet_link: 0.0
      right_arm_robotiq_arg2f_base_link: 0.0
      left_arm_robotiq_arg2f_base_link: 0.0
      left_arm_left_outer_finger: 0.0
      left_arm_right_outer_finger: 0.0
      right_arm_left_outer_finger: 0.0
      right_arm_right_outer_finger: 0.0
      left_arm_left_inner_finger: 0.0
      left_arm_right_inner_finger: 0.0
      right_arm_left_inner_finger: 0.0
      right_arm_right_inner_finger: 0.0
      left_arm_right_finger_mount: 0.0
      left_arm_left_finger_mount: 0.0
      left_arm_right_fingertip: 0.0
      left_arm_left_fingertip: 0.0
      right_arm_right_finger_mount: 0.0
      right_arm_left_finger_mount: 0.0
      right_arm_right_fingertip: 0.0
      right_arm_left_fingertip: 0.0
    self_collision_ignore: {
      base_link: [ewellix_lift_top_link, right_base_link, left_base_link],
      ewellix_lift_top_link: [right_base_link, left_base_link],
      right_base_link: [right_shoulder_link],
      left_base_link: [left_shoulder_link],
      right_shoulder_link: [right_half_arm_1_link],
      left_shoulder_link: [left_half_arm_1_link],
      right_half_arm_1_link: [right_half_arm_2_link],
      left_half_arm_1_link: [left_half_arm_2_link],
      right_half_arm_2_link: [right_forearm_link],
      left_half_arm_2_link: [left_forearm_link],
      right_forearm_link: [right_spherical_wrist_1_link],
      left_forearm_link: [left_spherical_wrist_1_link],
      right_spherical_wrist_1_link: [right_spherical_wrist_2_link],
      left_spherical_wrist_1_link: [left_spherical_wrist_2_link],
      right_spherical_wrist_2_link: [right_bracelet_link],
      left_spherical_wrist_2_link: [left_bracelet_link],
      right_bracelet_link: [right_arm_robotiq_arg2f_base_link],
      left_bracelet_link: [left_arm_robotiq_arg2f_base_link],
      right_arm_robotiq_arg2f_base_link: [right_arm_left_outer_finger, right_arm_right_outer_finger, right_arm_left_inner_finger, right_arm_right_inner_finger, right_arm_left_finger_mount, right_arm_right_fingertip, right_arm_right_finger_mount, right_arm_left_fingertip],
      left_arm_robotiq_arg2f_base_link: [left_arm_left_outer_finger, left_arm_right_outer_finger, left_arm_left_inner_finger, left_arm_right_inner_finger],
      left_arm_left_outer_finger: [left_arm_robotiq_arg2f_base_link, left_arm_right_outer_finger, left_arm_right_inner_finger, left_arm_left_finger_mount, left_arm_right_finger_mount],
      left_arm_right_outer_finger: [left_arm_robotiq_arg2f_base_link, left_arm_right_finger_mount, left_arm_left_finger_mount],
      right_arm_left_outer_finger: [right_arm_robotiq_arg2f_base_link, right_arm_right_outer_finger, right_arm_right_inner_finger, right_arm_left_finger_mount, left_arm_right_finger_mount],
      right_arm_right_outer_finger: [right_arm_robotiq_arg2f_base_link, right_arm_right_finger_mount, right_arm_left_finger_mount],
      left_arm_left_inner_finger: [left_arm_robotiq_arg2f_base_link, left_arm_left_outer_finger, left_arm_left_inner_knuckle],
      left_arm_right_inner_finger: [left_arm_robotiq_arg2f_base_link, left_arm_right_outer_finger, left_arm_right_inner_knuckle],
      right_arm_left_inner_finger: [right_arm_robotiq_arg2f_base_link, right_arm_left_outer_finger, right_arm_left_inner_knuckle, right_arm_right_outer_finger, right_arm_right_inner_knuckle, right_arm_right_inner_finger],
      right_arm_right_inner_finger: [right_arm_robotiq_arg2f_base_link, right_arm_right_outer_finger, right_arm_right_inner_knuckle, right_arm_left_outer_finger, right_arm_left_inner_knuckle],
      left_arm_right_finger_mount: [left_arm_right_outer_finger, left_arm_right_inner_finger, left_arm_right_fingertip,
      left_arm_right_inner_knuckle, left_arm_right_outer_knuckle],
      left_arm_left_finger_mount: [left_arm_left_outer_finger, left_arm_left_inner_finger, left_arm_left_fingertip,
      left_arm_left_inner_knuckle, left_arm_left_outer_knuckle, left_arm_right_fingertip],
      right_arm_right_finger_mount: [right_arm_right_outer_finger, right_arm_right_inner_finger, right_arm_right_fingertip, right_arm_left_outer_finger, right_arm_left_inner_finger, right_arm_left_inner_knuckle, right_arm_left_outer_knuckle,
      right_arm_right_inner_knuckle, right_arm_right_outer_knuckle, right_arm_left_finger_mount, right_arm_left_fingertip],
      right_arm_left_finger_mount: [right_arm_left_outer_finger, right_arm_left_inner_finger, right_arm_left_fingertip, right_arm_right_outer_finger, right_arm_right_inner_finger, right_arm_right_inner_knuckle, right_arm_right_outer_knuckle,
      right_arm_left_inner_knuckle, right_arm_left_outer_knuckle, right_arm_right_fingertip],
      left_arm_left_fingertip: [left_arm_left_finger_mount, left_arm_left_inner_finger, left_arm_left_outer_finger,
      left_arm_left_inner_knuckle, left_arm_left_outer_knuckle, left_arm_right_fingertip],
      left_arm_right_fingertip: [left_arm_right_finger_mount, left_arm_right_inner_finger, left_arm_right_outer_finger,
      left_arm_right_inner_knuckle, left_arm_right_outer_knuckle],
      right_arm_left_fingertip: [right_arm_left_finger_mount, right_arm_left_inner_finger, right_arm_left_outer_finger, right_arm_right_finger_mount, right_arm_right_inner_finger, right_arm_right_outer_finger, right_arm_right_inner_knuckle, right_arm_right_outer_knuckle,
      right_arm_left_inner_knuckle, right_arm_left_outer_knuckle, right_arm_right_fingertip],
      right_arm_right_fingertip: [right_arm_right_finger_mount, right_arm_right_inner_finger, right_arm_right_outer_finger, right_arm_left_finger_mount, right_arm_left_inner_finger, right_arm_left_outer_finger, right_arm_left_inner_knuckle, right_arm_left_outer_knuckle,
      right_arm_right_inner_knuckle, right_arm_right_outer_knuckle],
    }
    urdf_path: robot/frank_right_closed_description/frank_right_closed.urdf
    # usd_path: robots/frank/frank_static_soft_gripper.usd
    # isaac_usd_path: robots/frank/frank_static_soft_gripper.usd
    # usd_robot_root: /frank
    # use_usd_kinematics: True
    asset_root_path: "robot"

    lock_joints: null
    cspace:
      joint_names:
      - right_joint_1
      - left_joint_1
      - right_joint_2
      - left_joint_2
      - right_joint_3
      - left_joint_3
      - right_joint_4
      - left_joint_4
      - right_joint_5
      - left_joint_5
      - right_joint_6
      - left_joint_6
      - right_joint_7
      - left_joint_7
      # - right_arm_left_outer_knuckle_joint
      # - right_arm_right_outer_knuckle_joint
      # - left_arm_left_outer_knuckle_joint
      # - left_arm_right_outer_knuckle_joint
      # - right_arm_left_inner_finger_joint
      # - right_arm_right_inner_finger_joint
      # - left_arm_left_inner_finger_joint
      # - left_arm_right_inner_finger_joint
      # - right_arm_left_inner_knuckle_finger_joint
      # - right_arm_right_inner_knuckle_finger_joint
      # - left_arm_left_inner_knuckle_finger_joint
      # - left_arm_right_inner_knuckle_finger_joint
  
      cspace_distance_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0

    
      null_space_weight:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0
      # - 1.0

      retract_config: [
-0.6913,  0.8400,  1.6899,  1.2900,  2.4730, -1.6402,  1.1850,  1.1079,
          4.9969, -2.5751,  1.9255, -1.4772, -0.9188,  4.3717
      ]
      max_acceleration: 25.0
      max_jerk: 500.0
